title: Bancário News
description: "Notícias diárias para quem vive o mercado financeiro por dentro."
url: "https://setebot.github.io"
baseurl: "/bancarionews"
theme: minima
lang: pt-BR
author:
  name: SETE
  email: setebot@users.noreply.github.com

markdown: kramdown
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "SETE"
